# Deep Learning Foundational Exercise


[Original source](https://iamtrask.github.io/2015/07/12/basic-python-network/)


The idea is to be able to build this network from memory... No excuses!

## 2 Layers Neural Network

In [38]:
import numpy as np


In [39]:
def non_linear(x, diff=False):
    if diff:
        return x * (1 - x)
    return 1 / (1 + np.exp(- x))

In [40]:
X = np.array([[0,0,1], [0,1,1], [1,0,1], [1,1,1]])
Y = np.array([[0,0,1,1]]).T

In [41]:
np.random.seed(1)
W = 2 * np.random.random((3, 1)) - 1
W

array([[-0.16595599],
       [ 0.44064899],
       [-0.99977125]])

In [48]:
for i in range(10000):
    layer0 = X
    layer1 = non_linear(np.dot(layer0, W))
    loss = Y - layer1

    gradient = loss * non_linear(layer1, diff=True)
    
    W += np.dot(layer0.T, gradient)

In [55]:
non_linear(np.dot(X, W))

array([[0.00553603],
       [0.00451114],
       [0.99632027],
       [0.99548341]])

In [65]:
def non_linear(x, diff=False):
    if diff:
        return x * (1 - x)
    return 1 / (1 + np.exp(-x))

X = np.array([[0,0,1], [0,1,1], [1,0,1], [1,1,1]])
Y = np.array([[0,0,1,1]]).T
W = np.random.random((3,1))              

for i in range(10000):
    layer0 = X
    layer1 = non_linear(np.dot(layer0, W))
    loss = Y - layer1
    gradient = loss * non_linear(layer1, diff=True)
    W += np.dot(layer0.T, gradient)

non_linear(np.dot(X, W))    

array([[0.00966336],
       [0.00786382],
       [0.99359004],
       [0.99212055]])

In [86]:
def non_linear(x, diff=False):
    if diff:
        return x * (1 - x)
    return 1 / (1 + np.exp(-x))

X = np.array([[0,0,1], [0,1,1], [1,0,1], [1,1,1]])
Y = np.array([[0,0,1,1]]).T
W = 2 * np.random.random((3, 1)) - 1

for i in range(10000):
    layer0 = X
    layer1 = non_linear(np.dot(layer0, W))
    loss = Y - layer1
    gradient = loss * non_linear(layer1, diff=True)
    W += np.dot(layer0.T, gradient)

non_linear(np.dot(X, W))   


# loss.shape     4,1
# X.shape        4,3
# Y.shape        4,1
# gradient.shape 4,1
# non_linear(layer1, diff=True)    4,1
# W.shape        3,1  +=  X(T).gradient = (3,4).(4,1)
# layer1.shape   4,1  ----- X.W = (4,3).(3,1)

array([[0.00967088],
       [0.00786211],
       [0.99359268],
       [0.99211594]])

In [85]:
layer1.shape

(4, 1)

In [90]:
def non_linear(x, diff=False):
    if diff:
        return x * (1 - x)
    return 1 / (1 + np.exp(-x))

X = np.array([[0,0,1], [0,1,1], [1,0,1], [1,1,1]])
Y = np.array([[0,0,1,1]]).T
W = 2 * np.random.random((3,1)) - 1
for i in range(10000):
    l0 = X
    l1 = non_linear(np.dot(l0, W))
    loss = Y - l1
    gradient = loss * non_linear(l1, diff=True)
    W += np.dot(l0.T, gradient)
non_linear(np.dot(X, W))    

array([[0.0096673 ],
       [0.00786552],
       [0.9935889 ],
       [0.99211764]])

In [94]:
def nl(x, diff=False):
    if diff:
        return x * (1 - x)
    return 1 / (1 + np.exp(-x))
X = np.array([[0,0,1], [0,1,1], [1,0,1], [1,1,1]])
Y = np.array([[0,0,1,1]]).T
W = 2 * np.random.random((3,1)) - 1
for i in range(10000):
    l0 = X
    l1 = nl(np.dot(l0, W))
    loss = Y - l1
    grad = loss * nl(l1, diff=True)
    W += np.dot(l0.T, grad)
l1

array([[0.00966564],
       [0.0078644 ],
       [0.99358977],
       [0.99211894]])

In [2]:
import numpy as np
def nl(x, diff=False):
    if diff:
        return x * (1-x)
    return 1/(1+np.exp(-x))

x=np.array([[0,0,1], [0,1,1], [1,0,1], [1,1,1]])
y = np.array([[0,0,1,1]]).T
w = 10 * np.random.random((3,1))
for i in range(10000):
    l0=x
    l1=nl(np.dot(l0,w))
    # print(l1)
    loss=y-l1
    grad=loss*nl(l1, diff=True)
    w+=np.dot(l0.T, grad)
l1    

array([[0.00770514],
       [0.00558998],
       [0.99556246],
       [0.99388069]])

In [26]:
%reset -f
import numpy as np

def nl(x, diff=False):
    if diff:
        return x*(1-x)
    return 1/(1+np.exp(-x))

X = np.array([[0,0,1], 
              [1,0,1], 
              [0,1,1], 
              [1,1,1]])

Y = np.array([[0,0,1,1]]).T
W = 2 * np.random.random((3,1)) - 1
for i in range(10000):
    l0 = X
    l1 = nl(np.dot(X, W))
    loss = Y-l1
    grad = loss * nl(l1, diff=True)
    W += np.dot(l0.T, grad)
l1    

array([[0.00966743],
       [0.00786382],
       [0.99359057],
       [0.99211788]])

In [29]:
%reset -f
import numpy as np
def nl(x, diff=False):
    if diff:
        return x*(1-x)
    return 1/(1+np.exp(-x))

X = np.array([[0,0,1], 
              [1,0,1], 
              [0,1,1], 
              [1,1,1]])
Y = np.array([[0,1,0,1]]).T
W = 2 * np.random.random((3,1)) - 1
for i in range(10000):
    l0 = X
    l1 = nl(np.dot(X,W))
    loss = Y-l1
    grad = loss * nl(l1, diff=True)
    W += np.dot(l0.T, grad)
l1    

array([[0.00967043],
       [0.9935892 ],
       [0.00786562],
       [0.99211555]])

In [33]:
%reset -f
import numpy as np
def nl(x, diff=False):
    if diff:
        return x*(1-x)
    return 1/(1+np.exp(-x))
x=np.array([[0,0,1],
            [1,0,1],
            [0,1,1],
            [1,1,1]])
y = np.array([[0,1,0,1]]).T
w = 2*np.random.random((3,1))-1
for i in range(10000):
    l0=x
    l1=nl(np.dot(x,w))
    loss = y-l1
    grad = loss*nl(l1, diff=True)
    w+=np.dot(l0.T, grad)
l1    

array([[0.0096702 ],
       [0.99358983],
       [0.00786494],
       [0.99211583]])

In [34]:
%reset -f
import numpy as np
def nl(x, d=0):
    if d: return x*(1-x)
    return 1/(1+np.exp(-x))
x=np.array([[0,0,1],[1,0,1],[0,1,1],[1,1,1]])
y=np.array([[1,1,1,1]]).T
w=2*np.random.random((3,1))-1
for i in range(10000):
    l0=x
    l1=nl(np.dot(x,w))
    loss = y-l1
    grad = loss*nl(l1, d=1)
    w+=np.dot(x.T, grad)
l1    

array([[0.99357842],
       [0.99833792],
       [0.99764883],
       [0.9993933 ]])

In [39]:
%reset -f
import numpy as np
def nl(x, d=0):
    if d: return x*(1-x)
    return 1/(1+np.exp(-x))
x=np.array([[0,0,1],[1,0,1],[0,1,1],[1,1,1]])
y=np.array([[0,0,1,1]]).T
w=np.random.random((3,1))
for i in range(10000):
    l0=x
    l1=nl(np.dot(x,w))
    loss=y-l1
    grad=loss*nl(l1,d=1)
    w+=np.dot(x.T,grad)
l1    

array([[0.00966599],
       [0.00786474],
       [0.99358948],
       [0.99211865]])

In [42]:
%reset -f
import numpy as np
def nl(x,d=0):
    if d: return x*(1-x)
    return 1/(1+np.exp(-x))
x=np.array([[0,0,1],[1,0,1],[0,1,1],[1,1,1]])
y=np.array([[0,0,1,1]]).T
w=np.random.random((3,1))
for i in range(10000):
    l1=nl(np.dot(x,w))
    loss=y-l1
    grad=loss*nl(l1,d=1)
    w+=np.dot(x.T,grad)
l1    
#1

array([[0.00966837],
       [0.00786511],
       [0.99358944],
       [0.99211701]])

In [46]:
%reset -f
import numpy as np
def nl(x,d=0):
    if d:return x*(1-x)
    return 1/(1+np.exp(-x))
x=np.array([[0,0,1],[1,0,1],[0,1,1],[1,1,1]])
y=np.array([[0,0,1,1]]).T
w=np.random.random((3,1))
for i in range(10000):
    l1=nl(np.dot(x,w))
    loss=y-l1
    grad=loss*nl(l1,d=1)
    w+=np.dot(x.T,grad)
l1    
#2

array([[0.00966377],
       [0.00786417],
       [0.99358975],
       [0.99212022]])

In [1]:
%reset -f
import numpy as np
def nl(x,d=0):
    if d:return x*(1-x)
    return 1/(1+np.exp(-x))
x=np.array([[0,0,1],[1,0,1],[0,1,1],[1,1,1]])
y=np.array([[0,0,1,1]]).T
w=np.random.random((3,1))
for i in range(10000):
    l1=nl(np.dot(x,w))
    loss=y-l1
    grad=loss*nl(l1,d=1)
    w+=np.dot(x.T,grad)
l1    
#3 
nl(l1,d=1).shape

(4, 1)

## 3 Layers Neural Network

In [141]:
import numpy as np

def nl(x, diff=False):
    if diff:
        return x*(1-x)
    return 1/(1+np.exp(-x))

X = np.array([[0,0,1], [0,1,1], [1,0,1], [1,1,1]])
Y = np.array([[0,1,1,0]]).T
W0 = 2 * np.random.random((3,4)) - 1
W1 = 2 * np.random.random((4,1)) - 1
for i in range(10000):
    l0=X
    l1=nl(np.dot(l0, W0))
    l2=nl(np.dot(l1, W1))

    l2err = Y-l2
    l2grd = l2err * nl(l2, diff=True)
    
    l1err = np.dot(l2grd, W1.T)
    l1grd = l1err * nl(l1, diff=True)
    
    W1 += np.dot(l1.T, l2grd)
    W0 += np.dot(l0.T, l1grd)
    
    if (i % 1000) == 0:
        print("Error: ", str(np.mean(np.abs(l2err))))

l2        

Error:  0.5007555904730444
Error:  0.051402104544761094
Error:  0.028128406158195597
Error:  0.02117897890049429
Error:  0.017589205474840577
Error:  0.01532395906649446
Error:  0.013734261035357884
Error:  0.0125422366549304
Error:  0.011606950012091555
Error:  0.010848484878825664


array([[0.01060591],
       [0.99014355],
       [0.98991664],
       [0.01032771]])

In [4]:
%reset -f
import numpy as np
def nl(x,d=0):
    if d:return x*(1-x)
    return 1/(1+np.exp(-x))
x=np.array([[0,0,1],[1,0,1],[0,1,1],[1,1,1]])
y=np.array(([[0,1,1,0]])).T
w0=np.random.random((3,4))
w1=np.random.random((4,1))
for i in range(10000):
    l0=x
    l1=nl(np.dot(l0,w0))
    l2=nl(np.dot(l1,w1))
    
    l2err=y-l2
    l2grd=l2err*nl(l2,d=1)
    
    l1err=l2grd.dot(w1.T)
    l1grd=l1err*nl(l1,d=1)
    
    w1+=np.dot(l1.T,l2grd)
    w0+=np.dot(l0.T,l1grd)
l2

array([[0.01181094],
       [0.99294058],
       [0.98800711],
       [0.00966764]])

In [6]:
%reset -f
import numpy as np
def nl(x,d=0):
    if d:return x*(1-x)
    return 1/(1+np.exp(-x))
x=np.array([[0,0,1],[1,0,1],[0,1,1],[1,1,1]])
y=np.array([[0,1,1,0]]).T
w0=np.random.random((3,4))
w1=np.random.random((4,1))
for i in range(10000):
    l1=nl(np.dot(x,w0))
    l2=nl(np.dot(l1,w1))
    l2d=(y-l2)*nl(l2,d=1)
    l1d=l2d.dot(w1.T)*nl(l1,d=1)
    w1+=np.dot(l1.T,l2d)
    w0+=np.dot(x.T,l1d)
l2    

array([[0.00568759],
       [0.98897092],
       [0.99016974],
       [0.01141925]])

In [10]:
%reset -f
import numpy as np
x=np.array([[0,0,1],[1,0,1],[0,1,1],[1,1,1]])
y=np.array([[0,1,1,0]]).T
w0=np.random.random((3,4))
w1=np.random.random((4,1))
for i in range(10000):
    l1=1/(1+np.exp(-np.dot(x,w0)))
    l2=1/(1+np.exp(-np.dot(l1,w1)))
    l2d=(y-l2)*(l2*(1-l2))
    l1d=l2d.dot(w1.T)*(l1*(1-l1))
    w1+=np.dot(l1.T,l2d)
    w0+=np.dot(x.T,l1d)
l2

array([[0.00625963],
       [0.98513158],
       [0.98616131],
       [0.01753937]])

In [11]:
%reset -f
import numpy as np
x=np.array([[0,0,1],[1,0,1],[0,1,1],[1,1,1]])
y=np.array([[0,1,1,0]]).T
w0=np.random.random((3,4))
w1=np.random.random((4,1))
for i in range(10000):
    l1=1/(1+np.exp(-np.dot(x,w0)))
    l2=1/(1+np.exp(-np.dot(l1,w1)))
    l2d=(y-l2)*(l2*(1-l2))
    l1d=l2d.dot(w1.T)*(l1*(1-l1))
    w1+=np.dot(l1.T,l2d)
    w0+=np.dot(x.T,l1d)
l2    

array([[0.00395598],
       [0.9846429 ],
       [0.98346767],
       [0.01862739]])

In [12]:
%reset -f
import numpy as np
x=np.array([[0,0,1],[1,0,1],[0,1,1],[1,1,1]])
y=np.array([[0,1,1,0]]).T
w0=np.random.random((3,4))
w1=np.random.random((4,1))
for i in range(10000):
    l1=1/(1+np.exp(-np.dot(x,w0)))
    l2=1/(1+np.exp(-np.dot(l1,w1)))
    l2d=(y-l2)*l2*(1-l2)
    l1d=l2d.dot(w1.T)*l1*(1-l1)
    w1+=np.dot(l1.T,l2d)
    w0+=np.dot(x.T,l1d)
l2    

array([[0.0094719 ],
       [0.99036879],
       [0.98933498],
       [0.01090529]])